### PR TITLE
Added function to replace youtube link by embed code #36

### PR DESCRIPTION
**Pull request by MinerBigWhale**
Added a function to replace.
Maybe not the best code ever but works.
ToDo: call the function to replace ervery Youtube
I let you decide when would you do that

### CODE REVIEW

**Comment by TristanWiley** [comment]
Hey, I'm really sorry but could you fix merge conflicts? Just merged larger commits <3

**Comment by MinerBigWhale** [comment]
Yes, no problem, i'll be at home this afternoon.

**Comment by MinerBigWhale** [comment]
A little error in my git settings :)

**Comment by TristanWiley** [comment]
Hey @MinerBigWhale one last thing before I merge. Can you check out @rlemon's code in #36 and try to make it work the the MutationObserver? Sorry, no worries if not.

**Comment by rlemon** [comment]
@MinerBigWhale https://github.com/rlemon/se-chat-dark-theme-plus/commit/a7b8d07f0488bacfd768822dd221c870be135007 here is my code for this, I think the problem might be in the Mutation Observer, tbh I didn't really read the code I just found the observer and tossed my function in there. Here is how I build mine : 

```
        this.observer = new MutationObserver(record => this.defaultParser(record)).observe(container, {
            childList: true,
            subtree: true
        });
```

it's in a class object, so `this` isn't important. the defaultParser just hands the nodes off to my other parsers, so also isn't really important. I believe the problem is that it isn't listening on the subtree. @TristanWiley  try editing https://github.com/TristanWiley/So-Chat-Commander/blob/master/background.js#L142 this to add 'subtree:true' and see if it fixes it locally?

**Comment by MinerBigWhale** [comment]
Yes of courses i have to go work now but this evening i will check that

**Comment by TristanWiley** [comment]
@MinerBigWhale got it all done :)

**Comment by MinerBigWhale** [comment]
Great

**Pull request closed without merging**
