### PR TITLE
Refactor some sections & fix generated new line

### PR DESCRIPTION
**Pull request by jonathanGB**
- changed commands from an array to a map; makes code simpler and access to `Command` objects are done in `O(1)` rather than `O(n)`
- remove `<arr>.length` inside `.slice`, as it's not necessary
- restucture keydown listener to make it simpler and without code repetition

Ps: My text editor (_Atom_) automatically removed empty characters from empty lines, which explains why the first commit has lots of diffs, even though most of the changes are really "empty".

### CODE REVIEW

**Comment by jonathanGB** [comment]
Something I would do is change `command` to `Command`, to follow object styling in JS (_Array, Object, Function_) and many other languages when declaring classes.

If I have your go @TristanWiley, I can add it in this PR.

**Comment by jonathanGB** [comment]
Added a fix to issue #13 too.

**Comment by drobilc** [comment]
Good job!

**Comment by jonathanGB** [comment]
Thanks!

Do you want to change `command` to  `Command`, as mentioned previously?

**Comment by drobilc** [comment]
Yes.

**Comment by jonathanGB** [comment]
Ok, I will add that in a next PR. I was thinking to add a feature to go through the commands in the popup using _tabs_, so I could make it a single PR, that's alright?

**Comment by TristanWiley** [comment]
Sure :)

**Pull request merged**
